[vagrant]
172.19.224.1 ansible_port=2200

[vagrant:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.ssh/vagrant_key_stage2
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=30'
