# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network "forwarded_port", guest: 22, host: 2200, host_ip: "0.0.0.0", id: "ssh"
  config.vm.network "forwarded_port", guest: 3000, host: 3001, host_ip: "0.0.0.0"
  config.vm.network "forwarded_port", guest: 5000, host: 5001, host_ip: "0.0.0.0"
end
